### ISSUE TITLE
Possible to open next url on line?

### ISSUE THREAD

**Issue by cands** [dhruvasagar/vim-open-url#10]
Thanks for making this handy plugin! I have a question / feature request. A common usecase for me is that I want to open an url ahead of the cursor on the same line (e.g. the cursor is at the beginning of the line and the url is at the end of the same line). Is it possible to add functionality to jump to the next url ahead and then open it in one go, if there is no url under the cursor's current position (with gB)? 

Maybe this is already possible with a custom vim mapping, I tried some different alternatives but could not get it to work, tips are appreciated.

**Comment by dhruvasagar** [comment]
@cands I'll take a look and circle back here if I find something, but this would only be for the apis to open a url, for searching and other apis it doesn't quite apply.

**Comment by cands** [comment]
Thanks a lot for taking a look. Yes I agree it only seems interesting for the apis to open a url.

**Comment by cands** [comment]
Did you have any time to look into this, any tips?

**Comment by dhruvasagar** [comment]
@cands I have just pushed v0.5.3 which adds `OpenURLFind` and an api `open_url#find_url` to support this behavior. I haven't added a mapping yet because I couldn't think of a non conflicting key binding for it yet. Kindly take a look and let me know, I have also updated the documentation.

**Comment by cands** [comment]
@dhruvasagar Thank you very much for adding this functionality! I have done some quick tests and it seems to be working great, no issues encountered. For me this is perfect since I often put links in the middle or at the end of lines, hopefully other users will appreciate it too.
