### ISSUE TITLE
URL opens in Vim instead of browser

### ISSUE THREAD

**Issue by khatchad** [dhruvasagar/vim-open-url#12]
Hitting `gF` on a URL (containing an anchor) saves the HTML in a file and opens that file in Vim. I expect it to open the URL directly in my browser.

## Regression

- Removing the anchor seems to invoke the same behavior.\
- I have a similar problem with `gx`.

**Comment by dhruvasagar** [comment]
`gF` comes from vim and `gx` comes from netrw. Those aren't related to / provided by this plugin. If, however, you are suggesting to use these for mappings, then for that I would prefer if you override the mappings yourself in your vim config.

**Comment by khatchad** [comment]
I got `gF` from your `README.md` file [here](https://github.com/dhruvasagar/vim-open-url#vim-mappings-). Is this not how I am supposed to invoke your plug-in? Thanks for the help!

**Comment by dhruvasagar** [comment]
@khatchad There is mention of `gF` in the README.md
