### ISSUE TITLE
How to map <Plug>(open-url-browser) on lua based config?

### ISSUE THREAD

**Issue by thepenguinthatwants** [dhruvasagar/vim-open-url#14]
Hi,
your plugin works really nicely but I have gotten used into gx so much that its hard to change into <g> enter.

I tried to map it into

keymap('n', 'gx', '<Plug>(open-url-browser)', opts)

but it's not quite there.

When I try this , when my cursor is on the link, its still not opening it.
:OpenURLFind
It just says No URL found.

**Comment by dhruvasagar** [comment]
@thepenguinthatwants the mapping seems right, can you share an example of the link on which you're trying to test this ? The error you're getting indicates that it wasn't recognised as a valud url (which must begin with http(s))

**Comment by francozappa** [comment]
Thanks for the great plugin.

I have the same issue with :OpenURLFind so the problem might be related to the function itself and not the mapping?

@dhruvasagar what is a typical use case of OpenURLFind?

**Comment by thepenguinthatwants** [comment]
Ah so the problem is actually, that the OpenURLFind should be used when the cursor is not ON the link but a space before the URL.
Is it possible to make it open the url, when the cursor is on the url?

like http*cursor*s://www.google.com/
instead of 
*cursor* https://www.google.com/

**Comment by dhruvasagar** [comment]
@thepenguinthatwants sure

**Comment by thepenguinthatwants** [comment]
This is now remarkably more awesome! THANKS!!!
