### ISSUE TITLE
`gx` seems to do part of what this plugin does

### ISSUE THREAD

**Issue by alok** [dhruvasagar/vim-open-url#2]
If your cursor is on a URL, typing `gx` opens it with the default handler, or with whatever handler you configure. For example, typing it over the URL `http://google.com` opens chrome for me and goes to that page. The `http(s)://` is mandatory though.

I don't know if the URL handling part of your plugin is different, but I'd check out `:h gx` if you haven't already.

Thanks for the great plugins by the way. `tablemode` and `dotoo` have a permanent place in my dotfiles.

**Comment by dhruvasagar** [comment]
Hey I am aware of `gx`, it comes from `netrw`, however the idea of this plugin was to expose an API to be able to open urls in general (also cross platform), but they may not have to be within the content.

ex.) Search word under cursor in google / wikipedia with mappings `gG`, `gW`.

It's a very small plugin but I wanted to use it across a few other experimental plugins so I just extracted the API into it's own plugin.

PS: Thanks for the encouraging words! If my plugins made your work / life better, my job is done :).

**Comment by ghost** [comment]
Btw `gx` doesn't work for me. I'm sick and tired of debugging it.
This just works, so great job @dhruvasagar !

**Comment by jeremyxwing** [comment]
Same. For some reason gx is often broken these days. Particularly in nvim on macOS.
