### ISSUE TITLE
Special characters in URL are interpreted by visual mapping, giving wrong URL

### ISSUE THREAD

**Issue by nedbat** [dhruvasagar/vim-open-url#7]
I tried to open this URL with this plugin:
```
http://davidbau.com/conformal/#z%5E3%2Bt&z=2.25
```
If I place the cursor somewhere in that URL, and use `gx`, it opens properly.  If instead I select the URL with `viW`, and then `gx`, the `#` and `%` are interpreted as the current file name and alternate file name, so an incorrect URL was opened:
```
http://davidbau.com/conformal//private/tmp/testrecur.pyzwork/tweets.txt5E3work/tweets.txt2Bt&z=2.25
```
Is there a way to keep the visual mode mapping from interpreting those characters?

**Comment by dhruvasagar** [comment]
Will look into this.

**Comment by nedbat** [comment]
Hi, I have a related question.

I have these mappings:
```
nmap gc :OpenInChrome <cfile><CR>
xmap gc :<C-U>OpenInChrome <C-R>=open_url#get_selection()<CR><CR>
```
If I put the cursor on a URL with a hash mark in it, this mapping puts the hash in the ex command, where it is expanded as the alternate file name.  What's the right way to make the mapping I want?

**Comment by dhruvasagar** [comment]
Hi, these are better mappings for the above. I have also fixed a related issue which will escape the `#` and a few other similar special characters in the url appropriately when using the `open_url#open_in` API.

```viml
nmap gc :call open_url#open_in('Google Chrome', expand('<cfile>'))<CR>
xmap gc :call open_url#open_in('Google Chrome', open_url#get_selection())<CR>
```

**Comment by dhruvasagar** [comment]
@nedbat Please NOTE that this `open_url#open_in` and dependent functionality is only available for macos (as of yet)

**Comment by nedbat** [comment]
Thanks, my problem is fixed! :)
